const EnrollmentModel = require('../models/enrollmentModel');
const AuditModel = require('../models/auditModel');

const enrollStudent = async (req, res, next) => {
    const enrollData = req.body;
    const performer = req.user?.email || req.user?.username || req.user?.name || 'Unknown User';

    try {
        if (!enrollData.fullName || !enrollData.courseCode || !enrollData.programName || !enrollData.yearId || !enrollData.semesterId) {
            const error = new Error("Missing enrollment details");
            error.statusCode = 400;
            throw error;
        }

        // Grab the real ID generated by the database
        const newId = await EnrollmentModel.enroll(enrollData, performer);

        await AuditModel.logAction('enrollment', {
            performer,
            action: 'ENROLL_STUDENT',
            status: 'SUCCESS',
            student: enrollData.fullName,
            course: enrollData.courseCode,
            details: enrollData
        });

        // Send the real ID back to the frontend!
        res.status(200).json({ success: true, message: "Enrollment successful.", enrollmentId: newId });

    } catch (err) {
        await AuditModel.logAction('enrollment', {
            performer,
            action: 'ENROLL_FAILED',
            status: 'FAILURE',
            errorMessage: err.message,
            details: enrollData
        });
        next(err);
    }
};

const archiveEnrollment = async (req, res, next) => {
    const { id } = req.params; 
    const { isArchived } = req.body; 
    const performer = req.user?.email || req.user?.username || req.user?.name || 'Unknown User';

    try {
        if (id === undefined || isArchived === undefined) {
            const error = new Error("Missing enrollment ID or archive status");
            error.statusCode = 400;
            throw error;
        }

        await EnrollmentModel.setArchived(id, isArchived, performer);

        await AuditModel.logAction('enrollment', {
            performer,
            action: isArchived ? 'ARCHIVE_ENROLLMENT' : 'UNARCHIVE_ENROLLMENT',
            status: 'SUCCESS',
            enrollmentId: id,
            details: { id, isArchived }
        });

        res.status(200).json({ 
            success: true, 
            message: `Course successfully ${isArchived ? 'dropped' : 'restored'}.` 
        });

    } catch (err) {
        await AuditModel.logAction('enrollment', {
            performer,
            action: isArchived ? 'ARCHIVE_FAILED' : 'UNARCHIVE_FAILED',
            status: 'FAILURE',
            errorMessage: err.message,
            details: { id, isArchived }
        });
        next(err);
    }
};

module.exports = { enrollStudent, archiveEnrollment };